name: Pulumi CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
